### ISSUE TITLE
データ取り込みバッチで相談件数のデータが 1/20 以降取り込まれていない

### ISSUE THREAD

**Issue by misopeso** [codeforchiba/covid19#360]
## 起こっている問題 / The Problem

1日1回 Github Actions の仕組みで動かしている convert バッチで相談件数のデータ(= contacts) が 2021/1/19 を最後に data.json に格納されていない。元データのエクセル上にはデータが存在しているので、バッチ側に問題がありそう。

**Comment by k-hata** [comment]
む、これは時期的に思い当たるフシがあるので確認します。
(たぶん1年使う想定になってない)
