### ISSUE TITLE
「企業の皆様・はたらく皆様へ」ページの調整

### ISSUE THREAD

**Issue by misopeso** [codeforchiba/covid19#5]

**Comment by seitaro1227** [comment]
東京版ではこのページ
https://stopcovid19.metro.tokyo.lg.jp/worker

**Comment by seitaro1227** [comment]
ひとまずGoogleスプレッドシートでどの情報を乗せるか確定させて着手する

**Comment by seitaro1227** [comment]
共有範囲はCode for Chibaメンバーでひとまず作成。
https://docs.google.com/spreadsheets/d/1nrdvOkUK7J9FCfKnHOlBekAvYmHpHPqBc_N6qnQONJg/edit#gid=0

入力支援フォーム
https://forms.gle/vf5NyKxMdivRQ8gT7


これらのサイトから拾ってくる(?)
https://www.chiba-cci.or.jp/2020/02/%E6%96%B0%E5%9E%8B%E3%82%B3%E3%83%AD%E3%83%8A%E3%82%A6%E3%82%A4%E3%83%AB%E3%82%B9%E6%84%9F%E6%9F%93%E7%97%87%E9%96%A2%E9%80%A3%E6%83%85%E5%A0%B1/

https://www.city.chiba.jp/hokenfukushi/chiikifukushi/covidkasituke.html
