### ISSUE TITLE
モノレールデータのフォーマット変更対応

### ISSUE THREAD

**Issue by k-hata** [codeforchiba/covid19#532]
6月14日の週より、モノレールの提供データの形が変更される。
それに伴い「01_monorail_jsonを生成.ipynb」の内容を変更する必要がある。

1.フォーマットの変更内容
日本語で記載されていた期間について「開始日」、「終了日」にわけYYYY/MM/DD形式で表現
旧
![image](https://user-images.githubusercontent.com/3695706/121527521-74684500-ca35-11eb-8d8b-47a46aa99e5a.png)
新
![image](https://user-images.githubusercontent.com/3695706/121527589-85b15180-ca35-11eb-94e0-82aa552c4af2.png)

2.「01_monorail_jsonを生成.ipynb」に対する修正内容
開始日、終了日を次のフォーマットに変換(MM月DD日)
期間を次の内容で作成。「開始日」+「~」＋「終了日」

**Comment by seitaro1227** [comment]
* 日付のカラムが分かれる問題を対応しました。
* 01_monorail_jsonを生成_日付の変更.ipynb
  * CfCのみ見れるリンクです
  * https://colab.research.google.com/drive/1tEfkqwZKnIPOGEaaV_DPn0jaqG9GoNcb?authuser=1
* 対応の確認は、データきてから流して確認します。

**Comment by misopeso** [comment]
Python スクリプトは Git 管理されていないので、変更をトラッキングできないが、対応したスクリプトで作った JSON ファイルの PR がこちら。

https://github.com/codeforchiba/covid19/pull/535

Python スクリプトの管理は、今後の検討課題で。
