### ISSUE TITLE
各グラフの元データへのリンクの追加

### ISSUE THREAD

**Issue by k-hata** [codeforchiba/covid19#79]
元データがオープンデータ化されたので、各グラフから元データにリンクを貼る

**Comment by misopeso** [comment]
公開されているページ

https://www.city.chiba.jp/hokenfukushi/iryoeisei/seisaku/covid-19/kanjamatome.html

**Comment by misopeso** [comment]
一応データカタログからもたどれる

https://www.city.chiba.jp/opendata/index.php
